<a href="https://colab.research.google.com/github/Digvijay25/Bank-Marketing-Campaign/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.6.0+cu124'

In [2]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [3]:
scaler.ndim

0

In [4]:
scaler.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7, 8,],
                        [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [12]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [14]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.4248, 0.8021, 0.9636, 0.9226],
        [0.3215, 0.5384, 0.8067, 0.9730],
        [0.0301, 0.8772, 0.1724, 0.5879]])

In [15]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [17]:
random_image_size_tensor.size()

torch.Size([224, 224, 3])

In [19]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros.dtype

torch.float32

In [21]:
ones = torch.ones(size=(3,4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [22]:
ones.shape, ones.ndim

(torch.Size([3, 4]), 2)

In [25]:
zero_to_ten =  torch.arange(0, 10)
zero_to_ten.shape, zero_to_ten.ndim

(torch.Size([10]), 1)

In [26]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
float_32_tensor = torch.tensor([7.0, 8.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [28]:
float_16_tensor = torch.tensor([7.0, 8.0, 9.0],
                               dtype = torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
some_tensor = torch.rand(3, 5)

print(some_tensor)
print(some_tensor.shape)
print(some_tensor.ndim)
print(some_tensor.device)

tensor([[0.5397, 0.4831, 0.2016, 0.2123, 0.2511],
        [0.6780, 0.7399, 0.1015, 0.4313, 0.0660],
        [0.4996, 0.6527, 0.6264, 0.8926, 0.3133]])
torch.Size([3, 5])
2
cpu


In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [32]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [33]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [35]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
tensor

tensor([1, 2, 3])

In [37]:
torch.mul(tensor, tensor)

tensor([1, 4, 9])

In [38]:
tensor * tensor

tensor([1, 4, 9])

In [39]:
torch.matmul(tensor, tensor)

tensor(14)

In [40]:
tensor @ tensor

tensor(14)

In [41]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [42]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [43]:
torch.mm(tensor, tensor.T)

<ipython-input-43-e91e0661583d>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3725.)
  torch.mm(tensor, tensor.T)


RuntimeError: self must be a matrix

In [44]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [50]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=8) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 2.2595,  1.2380, -0.1997,  0.6665, -0.7400,  0.7964,  0.4267,  0.6104],
        [ 4.5145,  2.2058, -0.2241,  0.8086, -0.5308,  2.2903,  1.6631,  1.0926],
        [ 6.7696,  3.1736, -0.2486,  0.9506, -0.3216,  3.7842,  2.8995,  1.5748]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 8])


In [51]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.min(), x.max()

(tensor(0), tensor(90))

In [53]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [54]:
x.type(torch.float32).mean()

tensor(45.)

In [55]:
x.sum()

tensor(450)

In [56]:
x.dtype

torch.int64

In [57]:
x.type(torch.float32).dtype

torch.float32

In [58]:
tensor.argmax()

tensor(2)

In [59]:
tensor

tensor([1, 2, 3])

In [60]:
x.argmax()

tensor(9)